products = [
    {
        '_id': '1',
        'name': 'Airpods Wireless Bluetooth Headphones',
        'image': '/images/airpods.jpg',
        'description':
        'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
        'brand': 'Apple',
        'category': 'Electronics',
        'price': 89.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'Vn T shirts',
        'image': '/images/phone.jpg',
        'description':
        'T shirts crazy',
        'brand': 'Levents',
        'category': 'T shirt',
        'price': 599.99,
        'countInStock': 0,
        'rating': 4.0,
        'numReviews': 8,
    },
    {
        '_id': '3',
        'name': 'Cannon EOS 80D DSLR Camera',
        'image': '/images/camera.jpg',
        'description':
        'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
        'brand': 'Cannon',
        'category': 'Electronics',
        'price': 929.99,
        'countInStock': 5,
        'rating': 3,
        'numReviews': 12,
    },
    {
        '_id': '4',
        'name': 'Baggy Pants',
        'image': '/images/baggy.jpg',
        'description':
        'Baggy pants',
        'brand': 'Pink',
        'category': 'Pants',
        'price': 399.99,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '5',
        'name': 'Multipieces traniner',
        'image': '/images/mouse.jpg',
        'description':
        'Pull and Bear multipieces traniner',
        'brand': 'Pull and Bear',
        'category': 'Shoes',
        'price': 49.99,
        'countInStock': 7,
        'rating': 3.5,
        'numReviews': 10,
    },
    {
        '_id': '6',
        'name': 'Jordan 1',
        'image': '/images/jordan.jpg',
        'description':
        'Nike air jordan 1',
        'brand': 'Nike',
        'category': 'Shoes',
        'price': 29.99,
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
    },
]
